name: Build (Arduino CLI — ESP32 Marauder Rewired)

on:
  workflow_dispatch:
    inputs:
      board:
        type: choice
        description: "Select target board"
        options:
          - Generic ESP32
          - ESP32-S2
          - ESP32-S3
          - DOIT DevKit D32
          - M5StickC / M5StickC-Plus (base)
          - M5StickC Plus 2
          - Flipper Zero WiFi Dev Board
          - Flipper Zero Multi Board S3
          - OG / Old Hardware
          - Marauder Mini
          - Marauder v6
          - Marauder v6.1
          - Marauder Kit
          - Marauder v7
          - Marauder v7.1
          - FireBeetle2 ESP32-E
          - Rev Feather (ESP32-S2)
          - M5Cardputer
          - ESP32-C5 DevKitC-1
          - CYD 2432S028
          - CYD 2432S024 Guition
          - CYD 2432S028 (2 USB)
          - Dev Board Pro
          - ESP32 LDDB

      config:
        type: choice
        description: "Select config file"
        options:
          - generic_esp32.json
          - esp32_s2_generic.json
          - esp32_s3_generic.json
          - doit_devkit_d32.json
          - m5stickc_base.json
          - m5stickc_plus2.json
          - flipper_zero_wifi_dev_board.json
          - flipper_zero_multi_board_s3.json
          - old_hardware.json
          - marauder_mini.json
          - marauder_v6.json
          - marauder_v6_1.json
          - marauder_kit.json
          - marauder_v7.json
          - marauder_v7_1.json
          - firebeetle2_esp32e.json
          - rev_feather_s2.json
          - m5cardputer.json
          - esp32_c5_devkitc1.json
          - cyd_2432s028.json
          - cyd_2432s024_guition.json
          - cyd_2432s028_2usb.json
          - marauder_dev_board_pro.json
          - esp32_lddb.json

      filesystem:
        type: choice
        description: "Select filesystem (or leave default)"
        options:
          - default
          - spiffs
          - littlefs
        default: default

      partition:
        description: "Partition file from repo root/partitions/ (leave blank for default)"
        required: false
        default: ""

      core_version:
        description: "Arduino-ESP32 core version"
        required: true
        default: "2.0.11"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Map board name → FQBN
        id: map
        run: |
          case "${{ github.event.inputs.board }}" in
            "Generic ESP32")          echo "fqbn=esp32:esp32:esp32" ;;
            "ESP32-S2")               echo "fqbn=esp32:esp32:esp32s2" ;;
            "ESP32-S3")               echo "fqbn=esp32:esp32:esp32s3" ;;
            "DOIT DevKit D32")        echo "fqbn=esp32:esp32:d32" ;;
            "M5StickC / M5StickC-Plus (base)") echo "fqbn=esp32:esp32:m5stick-c" ;;
            "M5StickC Plus 2")        echo "fqbn=esp32:esp32:m5stick-c" ;;
            "Flipper Zero WiFi Dev Board") echo "fqbn=esp32:esp32:esp32s2" ;;
            "Flipper Zero Multi Board S3") echo "fqbn=esp32:esp32:esp32s3" ;;
            "OG / Old Hardware")      echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder Mini")          echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder v6")            echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder v6.1")          echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder Kit")           echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder v7")            echo "fqbn=esp32:esp32:esp32" ;;
            "Marauder v7.1")          echo "fqbn=esp32:esp32:esp32" ;;
            "FireBeetle2 ESP32-E")    echo "fqbn=esp32:esp32:dfrobot_firebeetle2_esp32e" ;;
            "Rev Feather (ESP32-S2)") echo "fqbn=esp32:esp32:esp32s2" ;;
            "M5Cardputer")            echo "fqbn=esp32:esp32:esp32s3" ;;
            "ESP32-C5 DevKitC-1")     echo "fqbn=esp32:esp32:esp32c5" ;;
            "CYD 2432S028")           echo "fqbn=esp32:esp32:d32" ;;
            "CYD 2432S024 Guition")   echo "fqbn=esp32:esp32:d32" ;;
            "CYD 2432S028 (2 USB)")   echo "fqbn=esp32:esp32:d32" ;;
            "Dev Board Pro")          echo "fqbn=esp32:esp32:d32" ;;
            "ESP32 LDDB")             echo "fqbn=esp32:esp32:d32" ;;
          esac >> $GITHUB_OUTPUT

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          export PATH="${GITHUB_WORKSPACE}/bin:$PATH"
          arduino-cli version

      - name: Configure & Install ESP32 Core
        run: |
          CORE_VER="${{ github.event.inputs.core_version }}"
          arduino-cli config init --additional-urls "https://github.com/espressif/arduino-esp32/releases/download/${CORE_VER}/package_esp32_dev_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp32:esp32@${CORE_VER}"
          arduino-cli core list

      - name: Prepare Sketch
        id: prep
        run: |
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          mkdir -p "$SKETCH_DIR"
          cp scaffold/*.ino "$SKETCH_DIR/esp32_marauder_rewired.ino"
          cp -r scaffold/* "$SKETCH_DIR/"
          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      - name: Compile
        run: |
          FQBN="${{ steps.map.outputs.fqbn }}"
          FSYS="${{ github.event.inputs.filesystem }}"
          PART="${{ github.event.inputs.partition }}"
          SKETCH_DIR="${{ steps.prep.outputs.sketch_dir }}"

          FLAGS=""
          if [ "$FSYS" = "spiffs" ]; then FLAGS="$FLAGS -DBOARD_BUILD_FILESYSTEM=SPIFFS"; fi
          if [ "$FSYS" = "littlefs" ]; then FLAGS="$FLAGS -DBOARD_BUILD_FILESYSTEM=LITTLEFS"; fi
          if [ -n "$PART" ]; then FLAGS="$FLAGS -DBOARD_PARTITION_FILE=\\\"partitions/$PART\\\""; fi

          echo "Compiling for $FQBN with flags: $FLAGS"
          arduino-cli compile --fqbn "$FQBN" "$SKETCH_DIR" --export-binaries --build-property compiler.cpp.extra_flags="$FLAGS"

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_${{ github.event.inputs.board }}_${{ github.sha }}
          path: _build/esp32_marauder_rewired/build/*/*.bin
          if-no-files-found: error
          retention-days: 14
