name: Build (Arduino CLI — ESP32 Marauder Rewired)

on:
  push:
    branches: [ main, master ]
    tags: [ "*" ]
  pull_request:
  workflow_dispatch:
    inputs:
      fqbn:
        description: "FQBN to compile (overrides matrix)"
        required: false
      core_version:
        description: "Arduino-ESP32 core version"
        required: false
        default: "2.0.11"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - esp32:esp32:esp32    # ESP32 Dev Module
          - esp32:esp32:esp32s2  # ESP32-S2 Dev Module
          - esp32:esp32:esp32s3  # ESP32-S3 Dev Module

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Configure Arduino CLI
        run: |
          CORE="${{ inputs.core_version || '2.0.11' }}"
          arduino-cli config init --additional-urls "https://github.com/espressif/arduino-esp32/releases/download/${CORE}/package_esp32_dev_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp32:esp32@${CORE}"
          arduino-cli core list

      # Optional libs (uncomment if/when you need them)
      # - name: Install Libraries
      #   run: |
      #     arduino-cli lib install ESP32Ping
      #     arduino-cli lib install "TFT_eSPI@2.5.34"

      - name: Prepare Sketch Folder (from scaffold/)
        id: prep
        shell: bash
        run: |
          set -e
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          mkdir -p "$SKETCH_DIR"

          # Entry point (.ino)
          cp scaffold/example_integration/main_demo_snippet.ino \
             "$SKETCH_DIR/esp32_marauder_rewired.ino"

          # Copy all .h/.hpp/.c/.cpp files next to the .ino (no rsync needed)
          find scaffold -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cpp" \) -print0 \
            | xargs -0 -I {} cp --parents "{}" "$SKETCH_DIR/"

          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT
          echo "Sketch contents:"
          find "$SKETCH_DIR" -maxdepth 3 -type f | sort

      - name: Compile (Arduino CLI)
        shell: bash
        run: |
          FQBN="${{ inputs.fqbn || matrix.fqbn }}"
          echo "Compiling for $FQBN"
          arduino-cli compile --fqbn "$FQBN" "${{ steps.prep.outputs.sketch_dir }}" --warnings none --export-binaries

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: rewired_${{ inputs.fqbn || matrix.fqbn }}_${{ github.sha }}
          path: |
            _build/esp32_marauder_rewired/build/*/*.bin
          if-no-files-found: warn
          retention-days: 7
