name: Build (Arduino CLI — ESP32 Marauder Rewired — Per-board FS/Partition)

on:
  workflow_dispatch:
    inputs:
      board:
        type: choice
        description: "Target board"
        default: "Generic ESP32"
        options:
          - Generic ESP32
          - Flipper Zero WiFi Dev Board
          - Flipper Zero Multi Board S3
          - OG Marauder
          - Marauder v6
          - Marauder v6.1
          - Marauder Kit
          - Marauder Mini
          - ESP32 LDDB
          - Marauder Dev Board Pro
          - M5StickCPlus
          - M5StickCPlus 2
          - Rev Feather
          - Marauder v7
          - Marauder CYD 2432S028
          - Marauder CYD 2432S024 GUITION
          - Marauder CYD 2432S028 2 USB
          - Marauder v7.1
          - M5Cardputer
          - ESP32-C5-DevKitC-1

      filesystem:
        type: choice
        description: "Filesystem override (blank = use per-board default → core default)"
        default: ""
        options: ["", "spiffs", "littlefs"]

      partition:
        type: choice
        description: "Partition CSV override (blank = per-board default → none)"
        default: ""
        options:
          - ""
          - hugeapp_1m_fs.csv
          - marauder_littlefs.csv
          - marauder_spiffs_ota.csv
          - min_littlefs_ota.csv
          - min_spiffs_ota.csv
          - ota_1m_fs.csv

      core_version:
        description: "Arduino-ESP32 core version"
        required: false
        default: "2.0.11"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          export PATH="${GITHUB_WORKSPACE}/bin:$PATH"
          arduino-cli version

      - name: Configure & Install ESP32 Core
        run: |
          CORE_VER="${{ github.event.inputs.core_version }}"
          arduino-cli config init --additional-urls "https://github.com/espressif/arduino-esp32/releases/download/${CORE_VER}/package_esp32_dev_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp32:esp32@${CORE_VER}"
          arduino-cli core list

      - name: Extract pre-bundled libs (lib.tar)
        run: |
          mkdir -p $HOME/Arduino/libraries
          tar -xf lib.tar -C $HOME/Arduino/libraries || true
          echo "User libs:"; ls -1 $HOME/Arduino/libraries || true

      - name: Create ESP32MarauderRegistry local library
        run: |
          set -e
          LIBDIR="$HOME/Arduino/libraries/ESP32MarauderRegistry"
          mkdir -p "$LIBDIR/src/registry"
          cp -r scaffold/registry/* "$LIBDIR/src/registry/" || true
          cat > "$LIBDIR/library.properties" <<'PROP'
          name=ESP32MarauderRegistry
          version=0.0.3
          architectures=*
          includes=registry/ToolRegistry.h
          PROP

      - name: Unpack display settings (optional)
        run: |
          if [ -f "display_settings.zip" ]; then
            mkdir -p "$HOME/Arduino/libraries/TFT_eSPI"
            unzip -o "display_settings.zip" -d "$HOME/Arduino/libraries/TFT_eSPI" >/dev/null
            echo "Unpacked display headers."
          else
            echo "display_settings.zip not found; skipping."
          fi

      # --- Resolve board → fqbn + TFT header (same mapping you provided) ---
      - name: Resolve board mapping
        id: map
        shell: bash
        run: |
          sel="${{ github.event.inputs.board }}"

          declare -A FQBN=(
            ["Flipper Zero WiFi Dev Board"]="esp32:esp32:esp32s2:PartitionScheme=min_spiffs,FlashSize=4M,PSRAM=enabled"
            ["Flipper Zero Multi Board S3"]="esp32:esp32:esp32s3:PartitionScheme=min_spiffs,FlashSize=4M"
            ["OG Marauder"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder v6"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder v6.1"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder Kit"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder Mini"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["ESP32 LDDB"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder Dev Board Pro"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["M5StickCPlus"]="esp32:esp32:m5stick-c:PartitionScheme=min_spiffs"
            ["M5StickCPlus 2"]="esp32:esp32:m5stick-c:PartitionScheme=min_spiffs"
            ["Rev Feather"]="esp32:esp32:esp32s2:PartitionScheme=min_spiffs,FlashSize=4M,PSRAM=enabled"
            ["Marauder v7"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder CYD 2432S028"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder CYD 2432S024 GUITION"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder CYD 2432S028 2 USB"]="esp32:esp32:d32:PartitionScheme=min_spiffs"
            ["Marauder v7.1"]="esp32:esp32:dfrobot_firebeetle2_esp32e:FlashSize=16M,PartitionScheme=min_spiffs,PSRAM=enabled"
            ["M5Cardputer"]="esp32:esp32:esp32s3:PartitionScheme=min_spiffs,FlashSize=8M,PSRAM=disabled"
            ["ESP32-C5-DevKitC-1"]="esp32:esp32:esp32c5:PartitionScheme=min_spiffs"
            ["Generic ESP32"]="esp32:esp32:esp32:PartitionScheme=min_spiffs"
          )

          declare -A TFT=(
            ["Flipper Zero WiFi Dev Board"]="false"
            ["Flipper Zero Multi Board S3"]="false"
            ["OG Marauder"]="true"
            ["Marauder v6"]="true"
            ["Marauder v6.1"]="true"
            ["Marauder Kit"]="true"
            ["Marauder Mini"]="true"
            ["ESP32 LDDB"]="false"
            ["Marauder Dev Board Pro"]="false"
            ["M5StickCPlus"]="true"
            ["M5StickCPlus 2"]="true"
            ["Rev Feather"]="true"
            ["Marauder v7"]="true"
            ["Marauder CYD 2432S028"]="true"
            ["Marauder CYD 2432S024 GUITION"]="true"
            ["Marauder CYD 2432S028 2 USB"]="true"
            ["Marauder v7.1"]="true"
            ["M5Cardputer"]="true"
            ["ESP32-C5-DevKitC-1"]="false"
            ["Generic ESP32"]="false"
          )

          declare -A TFTFILE=(
            ["OG Marauder"]="User_Setup_og_marauder.h"
            ["Marauder v6"]="User_Setup_og_marauder.h"
            ["Marauder v6.1"]="User_Setup_og_marauder.h"
            ["Marauder Kit"]="User_Setup_og_marauder.h"
            ["Marauder Mini"]="User_Setup_marauder_mini.h"
            ["M5StickCPlus"]="User_Setup_marauder_m5stickc.h"
            ["M5StickCPlus 2"]="User_Setup_marauder_m5stickcp2.h"
            ["Rev Feather"]="User_Setup_marauder_rev_feather.h"
            ["Marauder v7"]="User_Setup_dual_nrf24.h"
            ["Marauder CYD 2432S028"]="User_Setup_cyd_micro.h"
            ["Marauder CYD 2432S024 GUITION"]="User_Setup_cyd_guition.h"
            ["Marauder CYD 2432S028 2 USB"]="User_Setup_cyd_2usb.h"
            ["Marauder v7.1"]="User_Setup_dual_nrf24.h"
            ["M5Cardputer"]="User_Setup_marauder_m5cardputer.h"
          )

          echo "fqbn=${FQBN[$sel]}" >> $GITHUB_OUTPUT
          echo "tft=${TFT[$sel]}" >> $GITHUB_OUTPUT
          echo "tftfile=${TFTFILE[$sel]}" >> $GITHUB_OUTPUT

      # --- Optional: read defaults from manifest.json (filesystem/partition) ---
      - name: Install jq (for manifest parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Resolve per-board defaults (filesystem/partition)
        id: defaults
        shell: bash
        run: |
          sel="${{ github.event.inputs.board }}"
          override_fs="${{ github.event.inputs.filesystem }}"
          override_part="${{ github.event.inputs.partition }}"

          # 1) Try manifest.json
          FS=""
          PART=""
          if [ -f "scaffold/configs/manifest.json" ]; then
            FS=$(jq -r --arg L "$sel" '
                  .boards[] | select(.label == $L) | .defaults.filesystem // empty' scaffold/configs/manifest.json)
            PART=$(jq -r --arg L "$sel" '
                  .boards[] | select(.label == $L) | .defaults.partition // empty' scaffold/configs/manifest.json)
          fi

          # 2) Fallback hardcoded defaults (edit as you like)
          if [ -z "$FS" ]; then
            declare -A DFS=(
              ["Generic ESP32"]=""
              ["Flipper Zero WiFi Dev Board"]="spiffs"
              ["Flipper Zero Multi Board S3"]="spiffs"
              ["OG Marauder"]="spiffs"
              ["Marauder v6"]="spiffs"
              ["Marauder v6.1"]="spiffs"
              ["Marauder Kit"]="spiffs"
              ["Marauder Mini"]="spiffs"
              ["ESP32 LDDB"]=""
              ["Marauder Dev Board Pro"]=""
              ["M5StickCPlus"]="spiffs"
              ["M5StickCPlus 2"]="spiffs"
              ["Rev Feather"]="spiffs"
              ["Marauder v7"]="spiffs"
              ["Marauder CYD 2432S028"]="spiffs"
              ["Marauder CYD 2432S024 GUITION"]="spiffs"
              ["Marauder CYD 2432S028 2 USB"]="spiffs"
              ["Marauder v7.1"]="spiffs"
              ["M5Cardputer"]="spiffs"
              ["ESP32-C5-DevKitC-1"]="spiffs"
            )
            FS="${DFS[$sel]}"
          fi

          if [ -z "$PART" ]; then
            declare -A DPT=(
              ["Generic ESP32"]=""
              ["Flipper Zero WiFi Dev Board"]="min_spiffs_ota.csv"
              ["Flipper Zero Multi Board S3"]="min_spiffs_ota.csv"
              ["OG Marauder"]="marauder_spiffs_ota.csv"
              ["Marauder v6"]="marauder_spiffs_ota.csv"
              ["Marauder v6.1"]="marauder_spiffs_ota.csv"
              ["Marauder Kit"]="marauder_spiffs_ota.csv"
              ["Marauder Mini"]="min_spiffs_ota.csv"
              ["ESP32 LDDB"]=""
              ["Marauder Dev Board Pro"]=""
              ["M5StickCPlus"]="min_spiffs_ota.csv"
              ["M5StickCPlus 2"]="min_spiffs_ota.csv"
              ["Rev Feather"]="min_spiffs_ota.csv"
              ["Marauder v7"]="marauder_spiffs_ota.csv"
              ["Marauder CYD 2432S028"]="min_spiffs_ota.csv"
              ["Marauder CYD 2432S024 GUITION"]="min_spiffs_ota.csv"
              ["Marauder CYD 2432S028 2 USB"]="min_spiffs_ota.csv"
              ["Marauder v7.1"]="marauder_spiffs_ota.csv"
              ["M5Cardputer"]="min_spiffs_ota.csv"
              ["ESP32-C5-DevKitC-1"]="min_spiffs_ota.csv"
            )
            PART="${DPT[$sel]}"
          fi

          # 3) Apply user overrides if provided
          [ -n "$override_fs" ] && FS="$override_fs"
          [ -n "$override_part" ] && PART="$override_part"

          echo "fs=$FS" >> $GITHUB_OUTPUT
          echo "part=$PART" >> $GITHUB_OUTPUT
          echo "Resolved defaults => FS='$FS' PART='$PART' (after overrides)"

      - name: Prepare Sketch Folder
        id: prep
        run: |
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          mkdir -p "$SKETCH_DIR"
          cp scaffold/*.ino "$SKETCH_DIR/esp32_marauder_rewired.ino"
          cp -r scaffold/* "$SKETCH_DIR/"
          # bring in your configs.h from repo root
          if [ -f "configs.h" ]; then
            cp "configs.h" "$SKETCH_DIR/configs.h"
          fi
          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      - name: Configure TFT_eSPI header (if TFT board)
        if: steps.map.outputs.tft == 'true'
        run: |
          TE="$HOME/Arduino/libraries/TFT_eSPI"
          SEL="${{ steps.map.outputs.tftfile }}"
          if [ -n "$SEL" ]; then
            echo "// Auto-generated by workflow" > "$TE/User_Setup_Select.h"
            echo "#include <${SEL}>" >> "$TE/User_Setup_Select.h"
            echo "Using TFT_eSPI setup: $SEL"
          else
            echo "TFT was true but no header specified; continuing."
          fi

      - name: Compile (Arduino CLI)
        run: |
          FQBN="${{ steps.map.outputs.fqbn }}"
          SKETCH_DIR="${{ steps.prep.outputs.sketch_dir }}"
          EXTRA="-I$HOME/Arduino/libraries/ESP32MarauderRegistry/src"

          FS="${{ steps.defaults.outputs.fs }}"
          PART="${{ steps.defaults.outputs.part }}"

          BUILD_FLAGS=""
          [ -n "$FS" ] && BUILD_FLAGS="$BUILD_FLAGS --build-property board_build.filesystem=$FS"
          [ -n "$PART" ] && BUILD_FLAGS="$BUILD_FLAGS --build-property board_build.partitions=$PART"

          echo "FQBN: $FQBN"
          echo "Final FS: $FS | Final PART: $PART"
          arduino-cli compile \
            --fqbn "$FQBN" \
            "$SKETCH_DIR" \
            --warnings none \
            --export-binaries \
            --build-property compiler.cpp.extra_flags="$EXTRA" \
            --build-property compiler.c.extra_flags="$EXTRA" \
            $BUILD_FLAGS

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: fw_${{ github.event.inputs.board }}_${{ github.sha }}
          path: _build/esp32_marauder_rewired/build/*/*.bin
          if-no-files-found: warn
          retention-days: 14
