name: Build (Arduino CLI — ESP32 Marauder Rewired w/ Config)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:
    inputs:
      fqbn:
        description: 'FQBN (e.g., esp32:esp32:esp32s3)'
        required: false
        default: 'esp32:esp32:esp32s3'
      core_version:
        description: 'Arduino-ESP32 core (e.g., 2.0.11)'
        required: false
        default: '2.0.11'
      config_name:
        description: 'Config filename in scaffold/configs (e.g., marauder_mini.json)'
        required: false
        default: 'marauder_mini.json'
      custom_config_json:
        description: 'Optional: paste a full JSON to override config_name'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          export PATH="${GITHUB_WORKSPACE}/bin:$PATH"
          arduino-cli version

      - name: Configure & Install ESP32 Core
        env:
          CORE_VER: ${{ inputs.core_version }}
        run: |
          arduino-cli config init --additional-urls "https://github.com/espressif/arduino-esp32/releases/download/${CORE_VER}/package_esp32_dev_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp32:esp32@${CORE_VER}"
          arduino-cli core list

      # ---------- Libraries ----------
      - name: Ensure Arduino libraries folder
        run: mkdir -p "$HOME/Arduino/libraries"

      - name: Install ESP32Ping
        uses: actions/checkout@v4
        with:
          repository: marian-craciunescu/ESP32Ping
          ref: 1.6
          path: CustomESP32Ping

      - name: Install AsyncTCP
        uses: actions/checkout@v4
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP

      - name: Install MicroNMEA
        uses: actions/checkout@v4
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA

      - name: Install ESPAsyncWebServer (Custom from repo)
        run: |
          rm -rf "$HOME/Arduino/libraries/ESPAsyncWebServer"
          cp -r Custom/ESPAsyncWebServer "$HOME/Arduino/libraries/ESPAsyncWebServer"

      - name: Install TFT_eSPI
        uses: actions/checkout@v4
        with:
          repository: Bodmer/TFT_eSPI
          ref: V2.5.34
          path: CustomTFT_eSPI

      - name: Install XPT2046_Touchscreen
        uses: actions/checkout@v4
        with:
          repository: PaulStoffregen/XPT2046_Touchscreen
          ref: v1.4
          path: CustomXPT2046_Touchscreen

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v4
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.3.8
          path: CustomNimBLE-Arduino

      - name: Install other libs
        run: |
          arduino-cli lib install "ArduinoJson@6.18.2" "Adafruit NeoPixel@1.10.7" "LinkedList@1.3.3" "EspSoftwareSerial@8.1.0" "Adafruit BusIO@1.15.0" "Adafruit MAX1704X@1.0.2"
          for d in Custom*; do
            bn=$(basename "$d"); rm -rf "$HOME/Arduino/libraries/$bn"; mv "$d" "$HOME/Arduino/libraries/$bn";
          done

      # ---------- Local library for registry ----------
      - name: Create ESP32MarauderRegistry local library
        run: |
          set -e
          LIBDIR="$HOME/Arduino/libraries/ESP32MarauderRegistry"
          mkdir -p "$LIBDIR/src/registry"
          cp -r scaffold/registry/* "$LIBDIR/src/registry/" || true
          cat > "$LIBDIR/library.properties" <<'PROP'
          name=ESP32MarauderRegistry
          version=0.0.3
          architectures=*
          includes=registry/ToolRegistry.h
          PROP
          echo "Library tree:"; find "$LIBDIR/src" -maxdepth 3 -type f | sort

      # ---------- Select/prepare config ----------
      - name: Select config (file or custom JSON)
        id: cfg
        shell: bash
        run: |
          set -e
          mkdir -p scaffold/data scaffold/configs

          if [ -n "${{ inputs.custom_config_json }}" ]; then
            echo "${{ inputs.custom_config_json }}" > scaffold/configs/custom.json
            CONFIG_FILE="custom.json"
          else
            CONFIG_FILE="${{ inputs.config_name }}"
          fi

          test -f "scaffold/configs/$CONFIG_FILE" || { echo "::error ::Config not found: scaffold/configs/$CONFIG_FILE"; exit 1; }
          cp "scaffold/configs/$CONFIG_FILE" scaffold/data/config.json

          echo "config_file=$CONFIG_FILE" >> $GITHUB_OUTPUT

      # ---------- Prepare Sketch ----------
      - name: Prepare Sketch Folder (from scaffold/)
        id: prep
        shell: bash
        run: |
          set -e
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          mkdir -p "$SKETCH_DIR"

          INO_SRC=$(ls scaffold/*.ino | head -n 1)
          [ -n "$INO_SRC" ] || (echo "No .ino found at scaffold/ root"; exit 1)
          cp "$INO_SRC" "$SKETCH_DIR/esp32_marauder_rewired.ino"

          pushd scaffold >/dev/null
          find . -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cpp" -o -name "*.json" \) -print0 \
            | xargs -0 -I {} cp --parents "{}" "$SKETCH_DIR/"
          popd >/dev/null

          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      # ---------- Compile ----------
      - name: Compile (Arduino CLI)
        shell: bash
        run: |
          set -e
          FQBN="${{ inputs.fqbn }}"
          SKETCH_DIR="${{ steps.prep.outputs.sketch_dir }}"
          EXTRA="-I$HOME/Arduino/libraries/ESP32MarauderRegistry/src"
          echo "Compiling for $FQBN with config ${{ steps.cfg.outputs.config_file }}"
          arduino-cli compile \
            --fqbn "$FQBN" \
            "$SKETCH_DIR" \
            --warnings none \
            --export-binaries \
            --build-property compiler.cpp.extra_flags="$EXTRA" \
            --build-property compiler.c.extra_flags="$EXTRA"

      # ---------- Sanitize and Upload firmware artifact ----------
      - name: Sanitize firmware artifact name
        id: sanitize_fw
        run: |
          NAME="firmware_${{ inputs.fqbn }}_${{ github.sha }}"
          SAFE_NAME=$(echo "$NAME" | sed 's/[:<>|*?\\\/]/_/g')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.sanitize_fw.outputs.safe_name }}
          path: _build/esp32_marauder_rewired/build/*/*.bin
          if-no-files-found: warn
          retention-days: 14
          compression-level: 6
          overwrite: false
          include-hidden-files: false
