name: Build-with-configs (JSON)

on:
  workflow_dispatch:
    inputs:
      board_flag:
        description: "Board flag (default: MARAUDER_V7)"
        required: false
        default: "MARAUDER_V7"
      board_label:
        description: "Optional board_label override"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure system deps
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq unzip rsync

      # ---------- Stage sketch ----------
      - name: Prepare Sketch Folder
        id: prep
        shell: bash
        run: |
          set -euo pipefail
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          rm -rf "$SKETCH_DIR"; mkdir -p "$SKETCH_DIR"
          cp esp32_marauder_rewired.ino "$SKETCH_DIR/"
          cp -r menus "$SKETCH_DIR/"
          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      - name: Stage MarauderMenu library from staged sketch menus/
        shell: bash
        run: |
          set -euo pipefail
          SKETCH_DIR="${{ steps.prep.outputs.sketch_dir }}"
          SRC_DIR="$SKETCH_DIR/menus"
          DEST="$HOME/Arduino/libraries/MarauderMenu"
          if [ ! -d "$SRC_DIR" ]; then
            echo "::error::$SRC_DIR not found."
            exit 1
          fi

          echo "Creating local library at: $DEST"
          rm -rf "$DEST"
          mkdir -p "$DEST/src/menus"

          rsync -a "$SRC_DIR/" "$DEST/src/menus/"

          # Umbrella header
          {
            printf '%s\n' '#pragma once'
            printf '%s\n' '#include "menus/MenuTypes.h"'
            printf '%s\n' '#include "menus/ToolRegistry.h"'
            printf '%s\n' '#include "menus/RegistryInit.h"'
            printf '%s\n' '#include "menus/MenuFromRegistry.h"'
          } > "$DEST/src/MarauderMenu.h"

          # Unity link unit
          {
            printf '#define MARAUDER_MENU_UNITY_BUILD 1\n'
            printf '#include "menus/MenuFromRegistry.cpp"\n'
            printf '#include "menus/ToolRegistry.cpp"\n'
            printf '#include "menus/RegistryInit.cpp"\n'
          } > "$DEST/src/link_units.cpp"

          # library.properties
          {
            printf 'name=MarauderMenu\n'
            printf 'version=0.1.0\n'
            printf 'author=ESP32 Marauder Rewired\n'
            printf 'maintainer=ESP32 Marauder Rewired\n'
            printf 'sentence=Menu/registry components for ESP32 Marauder Rewired.\n'
            printf 'paragraph=Local library staged by CI.\n'
            printf 'category=Other\n'
            printf 'architectures=*\n'
            printf 'includes=MarauderMenu.h\n'
          } > "$DEST/library.properties"

          echo "Local library contents:"
          find "$DEST" -maxdepth 3 -type f | sed 's/^/  /'
