name: Build-with-configs (JSON)

on:
  workflow_dispatch:
    inputs:
      board_flag:
        description: "Board flag (default: MARAUDER_V7)"
        required: false
        default: "MARAUDER_V7"
      board_label:
        description: "Optional board_label override"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Debug repo layout
        run: |
          pwd
          ls -la
          ls -la scaffold || true
          ls -la scaffold/configs || true
          ls -la scaffold/configs/boards || true
          sed -n '1,120p' scaffold/configs/boards/boards_manifest.json || true

      - name: Export board env from JSON manifest
        run: |
          echo "BOARD_FLAG=${{ github.event.inputs.board_flag }}" >> $GITHUB_ENV
          echo "BOARD_LABEL=${{ github.event.inputs.board_label }}" >> $GITHUB_ENV
          python3 scaffold/tools/export_env_from_json.py >> $GITHUB_ENV 2>> exporter.err || true
          echo "----- exporter stderr -----"
          cat exporter.err || true

      - name: Ensure FLAG present (fallback to input or MARAUDER_V7)
        run: |
          if [ -z "$FLAG" ]; then
            if [ -n "${{ github.event.inputs.board_flag }}" ]; then
              echo "FLAG=${{ github.event.inputs.board_flag }}" >> $GITHUB_ENV
            else
              echo "FLAG=MARAUDER_V7" >> $GITHUB_ENV
            fi
          fi

      - name: Ensure FQBN set (fbqn fallback)
        run: |
          if [ -z "$FQBN" ]; then
            echo "::warning::FQBN empty; checking FBQN fallback"
            if [ -n "$FBQN" ]; then
              echo "FQBN=$FBQN" >> $GITHUB_ENV
            fi
          fi

      - name: Last-resort FQBN mapping (unblock MARAUDER_V7)
        run: |
          if [ -z "$FQBN" ]; then
            case "$FLAG" in
              MARAUDER_V7)   echo "FQBN=esp32:esp32:d32:PartitionScheme=min_spiffs" >> $GITHUB_ENV ;;
              MARAUDER_MINI) echo "FQBN=esp32:esp32:d32:PartitionScheme=min_spiffs" >> $GITHUB_ENV ;;
              *) echo "::error::FQBN not found for FLAG='$FLAG' and no fallback rule defined."; exit 1;;
            esac
            echo "::notice::Applied last-resort FQBN mapping for $FLAG"
          fi

      - name: Assert FQBN present
        run: |
          if [ -z "$FQBN" ]; then
            echo "::error::FQBN is empty after exporter+fallback ? check boards_manifest (fqbn/fbqn)."
            exit 1
          fi

      - name: Dump resolved env (debug)
        run: |
          env | sort | grep -E '^(FLAG|BOARD_LABEL|FQBN|CORE_VERSION|FILESYSTEM|PARTITION|ADDR|DISPLAY_|LIBS_)' || true

      # Always use a pinned CLI version (avoid "latest")
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: 0.35.3

      - name: Configure ESP32 board manager index
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      # Hard-pin the ESP32 core version
      - name: Force core version 2.0.11
        run: echo "CORE_VERSION=2.0.11" >> $GITHUB_ENV

      - name: Install ESP32 core (with retry)
        run: |
          set -e
          for i in 1 2 3; do
            arduino-cli core install esp32:esp32@${CORE_VERSION} \
              --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json && break || {
                echo "Install attempt $i failed; retrying in 5s..."
                sleep 5
              }
          done
          arduino-cli core list

      - name: Clean conflicting libraries (XPT touch/TFT leftovers)
        run: |
          LIBDIR="$HOME/Arduino/libraries"
          mkdir -p "$LIBDIR"
          cd "$LIBDIR"
          rm -rf XPT2049Touch XPT2046_Touchscreen TFT_eSPI || true

      - name: Extract pre-bundled libs (JSON-driven)
        shell: bash
        run: |
          set -euo pipefail
          JSON="scaffold/configs/libs/lib_list.json"
          ZIPROOT="scaffold/lib"
          LIBDIR="$HOME/Arduino/libraries"
          mkdir -p "$LIBDIR"

          if [ ! -f "$JSON" ]; then
            echo "::error ::$JSON not found"; exit 1
          fi

          python3 - <<'PY'
import json, os, zipfile
J="scaffold/configs/libs/lib_list.json"
Z="scaffold/lib"
D=os.path.expanduser("~/Arduino/libraries")
os.makedirs(D, exist_ok=True)
data=json.load(open(J))
for entry in data.get("libs", []):
    zipname=entry.get("zip"); desc=entry.get("desc","")
    if not zipname: continue
    zp=os.path.join(Z, zipname)
    if os.path.exists(zp):
        print(f"Unpacking {zipname} ({desc})")
        with zipfile.ZipFile(zp) as zf: zf.extractall(D)
    else:
        print(f"WARNING: {zipname} not found in {Z}, skipping ({desc})")
print("Installed libs in", D, ":", os.listdir(D))
PY

      ### STAGE & ASSERT THE SKETCH ###
      - name: Prepare Sketch Folder
        id: prep
        run: |
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          rm -rf "$SKETCH_DIR"; mkdir -p "$SKETCH_DIR"
          SRC_INO="$(ls scaffold/*.ino | head -n 1)"
          cp "$SRC_INO" "$SKETCH_DIR/esp32_marauder_rewired.ino"
          cp -r scaffold/* "$SKETCH_DIR/" || true
          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      - name: Assert sketch prepared
        run: |
          test -f "${{ steps.prep.outputs.sketch_dir }}/esp32_marauder_rewired.ino" || { echo "::error ::prepared .ino missing"; exit 1; }

      ### AUTOGEN HEADERS INTO THE PREPARED DIR ###
      - name: Generate config.h (JSON-driven)
        run: |
          python3 scaffold/tools/gen_user_config.py \
            --boards-json scaffold/configs/boards/boards_manifest.json \
            --defines-json scaffold/configs/defines/build_defines.json \
            --modules-json scaffold/configs/modules/modules_presets.json \
            --board-flag "$BOARD_FLAG" \
            --board-label "$BOARD_LABEL" \
            --out "${{ steps.prep.outputs.sketch_dir }}/.autogen/config.h"

      - name: Generate TFT_eSPI header (serial-only safe)
        run: |
          mkdir -p "${{ steps.prep.outputs.sketch_dir }}/.tft_setup"
          python3 scaffold/tools/gen_tft_setup_json.py \
            --boards-json scaffold/configs/boards/boards_manifest.json \
            --displays-json scaffold/configs/displays/display_presets.json \
            --pins-json scaffold/configs/pins/pin_presets.json \
            --board-label "$BOARD_LABEL" \
            --board-flag "$BOARD_FLAG" \
            --model "${DISPLAY_MODEL}" \
            --tft-enabled "${DISPLAY_ENABLED}" \
            --out-dir "${{ steps.prep.outputs.sketch_dir }}/.tft_setup"

      ### COMPILE ###
      - name: Compile (Arduino CLI)
        working-directory: ${{ steps.prep.outputs.sketch_dir }}
        shell: bash
        env:
          EXTRA_FLAGS: "-I${{ steps.prep.outputs.sketch_dir }}/.tft_setup -I${{ steps.prep.outputs.sketch_dir }}/.autogen ${DEFINES_BASE}"
        run: |
          set -euo pipefail
          if [ -z "${FQBN:-}" ]; then
            echo "::error::FQBN is empty at compile time; check earlier steps."
            exit 1
          fi

          FS="${{ steps.fs.outputs.fs }}"
          PART="${{ steps.fs.outputs.partition }}"
          PART_PROP=""
          if [ -n "$PART" ]; then
            PART_PROP="--build-property build.partitions=${PART%.csv}"
          fi

          echo "FQBN:       $FQBN"
          echo "Sketch dir: $(pwd)"
          echo "Filesystem: ${FS:-<default>}"
          echo "Partition:  ${PART:-<default>}"
          ls -la; ls -la .tft_setup || true; ls -la .autogen || true

          arduino-cli compile \
            --fqbn "$FQBN" \
            --warnings none \
            --export-binaries \
            --build-property "compiler.cpp.extra_flags=${EXTRA_FLAGS}" \
            ${PART_PROP} \
            --output-dir "$GITHUB_WORKSPACE/build_out" \
            .

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: fw-${{ env.FLAG }}-${{ env.CORE_VERSION }}-${{ env.DISPLAY_MODEL || 'serial' }}
          path: build_out
