name: Build (Arduino CLI — ESP32 Marauder Rewired)

on:
  workflow_dispatch:
    inputs:
      fqbn:
        description: 'FQBN (e.g., esp32:esp32:esp32s3)'
        required: false
        default: 'esp32:esp32:esp32s3'
      core_version:
        description: 'Arduino-ESP32 core (e.g., 2.0.11)'
        required: false
        default: '2.0.11'
      config_name:
        description: 'Config in scaffold/configs (e.g., marauder_mini.json)'
        required: false
        default: 'marauder_mini.json'
      custom_config_json:
        description: 'Optional JSON to override config_name (leave blank to skip)'
        required: false
        default: ''
      filesystem:
        description: 'Filesystem define (leave blank to use sketch default)'
        required: false
        type: choice
        options:
          - ''         # no define
          - spiffs
          - littlefs
        default: ''
      partition_csv:
        description: 'Partition CSV from ./partitions (leave blank for default core scheme)'
        required: false
        type: choice
        options:
          - ''                       # don’t copy a CSV
          - hugeapp_1m_fs.csv
          - marauder_littlefs.csv
          - marauder_spiffs_ota.csv
          - min_littlefs_ota.csv
          - min_spiffs_ota.csv
          - ota_1m_fs.csv
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          export PATH="${GITHUB_WORKSPACE}/bin:$PATH"
          arduino-cli version

      - name: Configure & Install ESP32 Core
        env:
          CORE_VER: ${{ inputs.core_version }}
        run: |
          arduino-cli config init --additional-urls "https://github.com/espressif/arduino-esp32/releases/download/${CORE_VER}/package_esp32_dev_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp32:esp32@${CORE_VER}"
          arduino-cli core list

      # Libraries (download your tar bundle and extract)
      - name: Download & Extract lib.tar
        run: |
          mkdir -p "$HOME/Arduino/libraries"
          echo "Downloading lib.tar from repo..."
          curl -L "https://github.com/AirysDark/ESP32_Marauder_Rewired/raw/main/lib.tar" -o lib.tar
          tar -xf lib.tar -C "$HOME/Arduino/libraries"
          echo "Libraries installed to $HOME/Arduino/libraries"
          ls -la "$HOME/Arduino/libraries"

      # Helper library from scaffold/registry
      - name: Create ESP32MarauderRegistry local library
        run: |
          set -e
          LIBDIR="$HOME/Arduino/libraries/ESP32MarauderRegistry"
          mkdir -p "$LIBDIR/src/registry"
          cp -r scaffold/registry/* "$LIBDIR/src/registry/" || true
          cat > "$LIBDIR/library.properties" <<'PROP'
          name=ESP32MarauderRegistry
          version=0.0.3
          architectures=*
          includes=registry/ToolRegistry.h
          PROP
          echo "Library tree:"; find "$LIBDIR/src" -maxdepth 3 -type f | sort

      # Config selection
      - name: Select config (file or custom JSON)
        id: cfg
        shell: bash
        run: |
          set -e
          mkdir -p scaffold/data scaffold/configs
          if [ -n "${{ inputs.custom_config_json }}" ]; then
            echo "${{ inputs.custom_config_json }}" > scaffold/configs/custom.json
            CONFIG_FILE="custom.json"
          else
            CONFIG_FILE="${{ inputs.config_name }}"
          fi
          test -f "scaffold/configs/$CONFIG_FILE" || { echo "::error ::Config not found: scaffold/configs/$CONFIG_FILE"; exit 1; }
          cp "scaffold/configs/$CONFIG_FILE" scaffold/data/config.json
          echo "config_file=$CONFIG_FILE" >> $GITHUB_OUTPUT

      # Prepare sketch & optional partitions.csv
      - name: Prepare Sketch Folder (from scaffold/)
        id: prep
        shell: bash
        run: |
          set -e
          SKETCH_DIR="${PWD}/_build/esp32_marauder_rewired"
          mkdir -p "$SKETCH_DIR"

          INO_SRC=$(ls scaffold/*.ino | head -n 1)
          [ -n "$INO_SRC" ] || (echo "No .ino found at scaffold/ root"; exit 1)
          cp "$INO_SRC" "$SKETCH_DIR/esp32_marauder_rewired.ino"

          pushd scaffold >/dev/null
          find . -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cpp" -o -name "*.json" \) -print0 \
            | xargs -0 -I {} cp --parents "{}" "$SKETCH_DIR/"
          popd >/dev/null

          # Optional partition CSV
          if [ -n "${{ inputs.partition_csv }}" ]; then
            SRC="partitions/${{ inputs.partition_csv }}"
            if [ ! -f "$SRC" ]; then
              echo "::error ::Partition CSV not found at $SRC"; exit 1;
            fi
            cp "$SRC" "$SKETCH_DIR/partitions.csv"
            echo "Using custom partition table: $SRC -> $SKETCH_DIR/partitions.csv"
          else
            echo "No custom partition CSV selected; using core default."
          fi

          echo "sketch_dir=$SKETCH_DIR" >> $GITHUB_OUTPUT

      # Compile with optional FS define
      - name: Compile (Arduino CLI)
        shell: bash
        run: |
          set -e
          FQBN="${{ inputs.fqbn }}"
          SKETCH_DIR="${{ steps.prep.outputs.sketch_dir }}"

          # Optional filesystem define (blank -> no define, use sketch defaults)
          FSDEF=""
          case "${{ inputs.filesystem }}" in
            littlefs|LITTLEFS) FSDEF="-DFS_LITTLEFS=1" ;;
            spiffs|SPIFFS)     FSDEF="-DFS_SPIFFS=1" ;;
            "")                FSDEF="" ;;  # no define
            *) echo "::error ::Unsupported filesystem: ${{ inputs.filesystem }} (use blank, spiffs, or littlefs)"; exit 1 ;;
          esac

          EXTRA_INCL="-I$HOME/Arduino/libraries/ESP32MarauderRegistry/src"

          echo "Compiling for: $FQBN"
          echo "Filesystem:    '${{ inputs.filesystem }}' (defines: '$FSDEF')"
          if [ -f "$SKETCH_DIR/partitions.csv" ]; then
            echo "Custom partitions.csv present (auto-used by ESP32 core)."
          else
            echo "No partitions.csv (using FQBN/core default)."
          fi

          arduino-cli compile \
            --fqbn "$FQBN" \
            "$SKETCH_DIR" \
            --warnings none \
            --export-binaries \
            --build-property compiler.cpp.extra_flags="$EXTRA_INCL $FSDEF" \
            --build-property compiler.c.extra_flags="$EXTRA_INCL $FSDEF"

      # Upload firmware
      - name: Sanitize firmware artifact name
        id: sanitize_fw
        run: |
          NAME="firmware_${{ inputs.filesystem || 'defaultfs' }}_${{ inputs.partition_csv || 'defaultpart' }}_${{ inputs.fqbn }}_${{ github.sha }}"
          SAFE_NAME=$(echo "$NAME" | sed 's/[:<>|*?\\\/]/_/g')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.sanitize_fw.outputs.safe_name }}
          path: _build/esp32_marauder_rewired/build/*/*.bin
          if-no-files-found: warn
          retention-days: 14
          compression-level: 6
          overwrite: false
          include-hidden-files: false
